COLLECTION_TOYDATA = {
    {
        hash = "8473970491747",
        itemID = 1973,
        spellID = 16739,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[Может быть получена с добычи многих существ и сундуков старого мира Азерота.]],
        holidayText = "",
    },
    {
        hash = "57462367471584",
        itemID = 13379,
        spellID = 18400,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {10558},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 1,
        priceText = "|cFFFFD200Источник: |rПевчий Форрестен|n|cFFFFD200Зона: |rСтратхольм|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "76072460768600",
        itemID = 17712,
        spellID = 21848,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {6984},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 8,
        priceText = "|cFFFFD200Задание: |rБлагодарность от 'Пастбищ Дымного Леса'!|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "76089640637871",
        itemID = 17716,
        spellID = 21935,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {21940},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "80144089766486",
        itemID = 18660,
        spellID = 23126,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {23129},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "81535659170706",
        itemID = 18984,
        spellID = 23442,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {23486},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "81544249105309",
        itemID = 18986,
        spellID = 23453,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {23489},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "92513595582105",
        itemID = 21540,
        spellID = 26265,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {8868},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 8,
        priceText = "|cFFFFD200Задание: |rБлагословение Элуны|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Лунный фестиваль",
    },
    {
        hash = "102078487754293",
        itemID = 23767,
        spellID = 30261,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {30337},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "131176891191322",
        itemID = 30542,
        spellID = 36890,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {36954},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "131185481125965",
        itemID = 30544,
        spellID = 36941,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {36955},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "131812546351586",
        itemID = 30690,
        spellID = 37346,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {10675},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 8,
        priceText = "|cFFFFD200Задание: |rПопомните гномскую доброту!|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "139766825786959",
        itemID = 32542,
        spellID = 40527,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 2,
        price = 150,
        shopCategory = 0,
        productID = 21558,
        isActive = 1,
        lootType = 15,
        priceText = "|cFFFFD200Нужно очков голосования: |r150|TInterface\\Store\\mmotop.BLP:16:16|t",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "139869905002066",
        itemID = 32566,
        spellID = 40530,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 2,
        price = 150,
        shopCategory = 0,
        productID = 21581,
        isActive = 1,
        lootType = 15,
        priceText = "|cFFFFD200Источник: |rБыло замечено на черном рынке|n|n|cFFFFD200Цена: |r|n|cFFFFD200Нужно очков голосования: |r150|TInterface\\Store\\mmotop.BLP:16:16|t",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "140797617938773",
        itemID = 32782,
        spellID = 41301,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {21838},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 1,
        priceText = "|cFFFFD200Источник: |rТерокк|n|cFFFFD200Зона: |rПокой Терокка(Лес Тероккар)|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "142073223226749",
        itemID = 33079,
        spellID = 42365,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 2,
        price = 240,
        shopCategory = 0,
        productID = 21551,
        isActive = 1,
        lootType = 15,
        priceText = "|cFFFFD200Нужно очков голосования: |r240|TInterface\\Store\\mmotop.BLP:16:16|t",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "142674518648577",
        itemID = 33219,
        spellID = 42753,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "142691698517774",
        itemID = 33223,
        spellID = 42766,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 17,
        priceText = "|cFFFFD200Источник: |rБыло замечено на черном рынке|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "145715355495200",
        itemID = 33927,
        spellID = 43808,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {27478,27489,23710,24495},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЛаркин Громовар, Рай'ма, Белби Быстросмен, Бликс Чиништукс|n|cFFFFD200Зона: |rДун Морог,|nФерма Каменного Клыка(Дуротар),|nСтальгорн,|nОргриммар|n|cFFFFD200Цена: |r100 |TInterface\\Icons\\INV_Misc_Coin_01.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Хмельной фестиваль",
    },
    {
        hash = "148090472411174",
        itemID = 34480,
        spellID = 45094,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {37674},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rМилая продавщица|n|cFFFFD200Зона: |rОргриммар,|nГромовой Утес,|nПодгород,|nЛуносвет|n|cFFFFD200Цена: |r10 |TInterface\\Icons\\INV_ValentinesCard01.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Любовная лихорадка",
    },
    {
        hash = "148172076789839",
        itemID = 34499,
        spellID = 45135,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {7936},
        currency = 2,
        price = 150,
        shopCategory = 0,
        productID = 21582,
        isActive = 1,
        lootType = 15,
        priceText = "|cFFFFD200Задание: |r1000 купонов – Складной бумажный ветролет|n|n|cFFFFD200Цена: |r|n|cFFFFD200Нужно очков голосования: |r150|TInterface\\Store\\mmotop.BLP:16:16|t",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Ярмарка Новолуния",
    },
    {
        hash = "148975235674482",
        itemID = 34686,
        spellID = 45426,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {26124,26123},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rТорговка праздника Огненного солнцеворота, Поставщица праздника Огненного солнцеворота|n|cFFFFD200Зона: |rДеревня Рут'теран(Тельдрассил),|nЭкзодар,|nСтальгорн,|nШтормград|n|cFFFFD200Цена: |r350 |TInterface\\Icons\\INV_SummerFest_FireFlower.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Огненный солнцеворот",
    },
    {
        hash = "151298812982395",
        itemID = 35227,
        spellID = 46203,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {101410},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 3,
        priceText = "|cFFFFD200Источник: |rМешок сокровищ монаха|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "151504971412754",
        itemID = 35275,
        spellID = 46354,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "158321084512928",
        itemID = 36862,
        spellID = 47776,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[Можно найти у многих существ Нордскола при обшаривании карманов.]],
        holidayText = "",
    },
    {
        hash = "158325379480218",
        itemID = 36863,
        spellID = 47770,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[Можно найти у многих существ Нордскола при обшаривании карманов.]],
        holidayText = "",
    },
    {
        hash = "160004711693516",
        itemID = 37254,
        spellID = 48332,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[Может быть получена с добычи многих существ Нордскола.]],
        holidayText = "",
    },
    {
        hash = "160889474956882",
        itemID = 37460,
        spellID = 48722,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {28951},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rБреанни|n|cFFFFD200Зона: |rДаларан|n|cFFFFD200Цена: |r0.75 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "161963216781512",
        itemID = 37710,
        spellID = 49352,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {21313},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 3,
        priceText = "|cFFFFD200Источник: |rПодарок в фирменной упаковке|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "164501542454413",
        itemID = 38301,
        spellID = 50317,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 17,
        priceText = "|cFFFFD200Источник: |rБыло замечено на черном рынке|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "165691248396728",
        itemID = 38578,
        spellID = 51640,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 17,
        priceText = "|cFFFFD200Источник: |rБыло замечено на черном рынке|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "175097226778038",
        itemID = 40768,
        spellID = 54710,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {56472},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "186826782467205",
        itemID = 43499,
        spellID = 58501,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {29744,30472},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rРорк Остробород, Олут Пивобрюх|n|cFFFFD200Зона: |rЛедяная крепость(Грозовая Гряда),|nМесто крушения Гром'арша(Грозовая Гряда)|n|cFFFFD200Цена: |r10 |TInterface\\Icons\\INV_Misc_Rune_14.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "188222646839221",
        itemID = 43824,
        spellID = 59317,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {1956},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 7,
        priceText = "|cFFFFD200Достижение: |rУченье – свет!|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "190825397021738",
        itemID = 44430,
        spellID = 60458,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {2096},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 7,
        priceText = "|cFFFFD200Достижение: |rЛовец монеток|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "191581311266407",
        itemID = 44606,
        spellID = 61031,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {29716,29478},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЗаводной помощник, Джепетто Таратор|n|cFFFFD200Зона: |rДаларан|n|cFFFFD200Цена: |r250 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "192066642571164",
        itemID = 44719,
        spellID = 61340,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {44718},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 3,
        priceText = "|cFFFFD200Источник: |rКувшин перебродившей гадости|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "192500434268576",
        itemID = 44820,
        spellID = 61856,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {28951},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rБреанни|n|cFFFFD200Зона: |rДаларан|n|cFFFFD200Цена: |r1.5 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193320773022992",
        itemID = 45011,
        spellID = 62736,
        isUsable = true,
        factionSide = 5,
        unique = {},
        colorData = {},
        ownersList = {33307},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rКапрал Артур Флю|n|cFFFFD200Зона: |rПавильон Серебряного союза(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193329362957593",
        itemID = 45013,
        spellID = 62745,
        isUsable = true,
        factionSide = 6,
        unique = {},
        colorData = {},
        ownersList = {33556},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rДору Громовой Рог|n|cFFFFD200Зона: |rПавильон Похитителей Солнца(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193333657924886",
        itemID = 45014,
        spellID = 62742,
        isUsable = true,
        factionSide = 6,
        unique = {},
        colorData = {},
        ownersList = {33553},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rФрека Кровавый Топор|n|cFFFFD200Зона: |rПавильон Похитителей Солнца(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193337952892178",
        itemID = 45015,
        spellID = 62738,
        isUsable = true,
        factionSide = 6,
        unique = {},
        colorData = {},
        ownersList = {33554},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rСамамба|n|cFFFFD200Зона: |rПавильон Похитителей Солнца(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193342247859479",
        itemID = 45016,
        spellID = 62743,
        isUsable = true,
        factionSide = 6,
        unique = {},
        colorData = {},
        ownersList = {33555},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЭлиза Киллиан|n|cFFFFD200Зона: |rПавильон Похитителей Солнца(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193346542826776",
        itemID = 45017,
        spellID = 62744,
        isUsable = true,
        factionSide = 6,
        unique = {},
        colorData = {},
        ownersList = {33557},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rТреллис Утреннее Солнце|n|cFFFFD200Зона: |rПавильон Похитителей Солнца(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193350837794065",
        itemID = 45018,
        spellID = 62737,
        isUsable = true,
        factionSide = 5,
        unique = {},
        colorData = {},
        ownersList = {33310},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rДеррик Пегобород|n|cFFFFD200Зона: |rПавильон Серебряного союза(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193355132761365",
        itemID = 45019,
        spellID = 62741,
        isUsable = true,
        factionSide = 5,
        unique = {},
        colorData = {},
        ownersList = {33650},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rРилли Веретень|n|cFFFFD200Зона: |rПавильон Серебряного союза(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193359427728660",
        itemID = 45020,
        spellID = 62740,
        isUsable = true,
        factionSide = 5,
        unique = {},
        colorData = {},
        ownersList = {33657},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rИризи|n|cFFFFD200Зона: |rПавильон Серебряного союза(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193363722695955",
        itemID = 45021,
        spellID = 62739,
        isUsable = true,
        factionSide = 5,
        unique = {},
        colorData = {},
        ownersList = {33653},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rРуок Хищная Хватка|n|cFFFFD200Зона: |rПавильон Серебряного союза(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193518341518821",
        itemID = 45057,
        spellID = 62949,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {29716,29478},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЗаводной помощник, Джепетто Таратор|n|cFFFFD200Зона: |rДаларан|n|cFFFFD200Цена: |r250 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "193544111322633",
        itemID = 45063,
        spellID = 62985,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 17,
        priceText = "|cFFFFD200Источник: |rБыло замечено на черном рынке|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "197499776203649",
        itemID = 45984,
        spellID = 64385,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {46007},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 3,
        priceText = "|cFFFFD200Источник: |rМешок рыбацких сокровищ|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "200918570172663",
        itemID = 46780,
        spellID = 65783,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 2,
        price = 150,
        shopCategory = 0,
        productID = 21583,
        isActive = 1,
        lootType = 15,
        priceText = "|cFFFFD200Нужно очков голосования: |r150|TInterface\\Store\\mmotop.BLP:16:16|t",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "201189153112769",
        itemID = 46843,
        spellID = 66241,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {34885},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rКавалер-дама Эвники Капсалис|n|cFFFFD200Зона: |rСеребряный павильон(Ледяная Корона)|n|cFFFFD200Цена: |r15 |TInterface\\Icons\\Ability_Paladin_ArtofWar.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "210165634763001",
        itemID = 48933,
        spellID = 67833,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {67920},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "213472759543249",
        itemID = 49703,
        spellID = 30161,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 2,
        price = 150,
        shopCategory = 0,
        productID = 21579,
        isActive = 1,
        lootType = 15,
        priceText = "|cFFFFD200Нужно очков голосования: |r150|TInterface\\Store\\mmotop.BLP:16:16|t",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "213477054510551",
        itemID = 49704,
        spellID = 30167,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 2,
        price = 240,
        shopCategory = 0,
        productID = 21580,
        isActive = 1,
        lootType = 15,
        priceText = "|cFFFFD200Нужно очков голосования: |r240|TInterface\\Store\\mmotop.BLP:16:16|t",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "216771294468325",
        itemID = 50471,
        spellID = 71909,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {54537},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 3,
        priceText = "|cFFFFD200Источник: |rКоробочка в виде сердца|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Любовная лихорадка",
    },
    {
        hash = "224201587891816",
        itemID = 52201,
        spellID = 73320,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {24917},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 8,
        priceText = "|cFFFFD200Задание: |rПлач Мурадина|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "224424926191219",
        itemID = 52253,
        spellID = 73331,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {24918},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 8,
        priceText = "|cFFFFD200Задание: |rВозмездие Сильваны|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "232838767125642",
        itemID = 54212,
        spellID = 74890,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "233401407841639",
        itemID = 54343,
        spellID = 75111,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {29716,29478},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЗаводной помощник, Джепетто Таратор|n|cFFFFD200Зона: |rДаларан|n|cFFFFD200Цена: |r40 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "233805134754392",
        itemID = 54437,
        spellID = 62040,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {29716,29478},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЗаводной помощник, Джепетто Таратор|n|cFFFFD200Зона: |rДаларан|n|cFFFFD200Цена: |r10 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "233809429734783",
        itemID = 54438,
        spellID = 75135,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {29716,29478},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЗаводной помощник, Джепетто Таратор|n|cFFFFD200Зона: |rДаларан|n|cFFFFD200Цена: |r10 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "233869559276928",
        itemID = 54452,
        spellID = 75136,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "234724257769227",
        itemID = 54651,
        spellID = 75531,
        isUsable = true,
        factionSide = 1,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "234732847703820",
        itemID = 54653,
        spellID = 75532,
        isUsable = true,
        factionSide = 2,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "249258427342824",
        itemID = 58035,
        spellID = 319464,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "249262722310121",
        itemID = 58036,
        spellID = 319465,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "430201104556446",
        itemID = 100164,
        spellID = 319902,
        isUsable = true,
        factionSide = 5,
        unique = {},
        colorData = {},
        ownersList = {81302,11504},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЭккирк, Иррсикк|n|cFFFFD200Зона: |rШтормград,|nОргриммар,|nПлощадь Руноплета(Даларан),|nБухта торговцев|n|cFFFFD200Цена: |r50000 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "430205399523743",
        itemID = 100165,
        spellID = 319903,
        isUsable = true,
        factionSide = 6,
        unique = {},
        colorData = {},
        ownersList = {81302,11504},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rЭккирк, Иррсикк|n|cFFFFD200Зона: |rШтормград,|nОргриммар,|nПлощадь Руноплета(Даларан),|nБухта торговцев|n|cFFFFD200Цена: |r50000 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "439418104365305",
        itemID = 102310,
        spellID = 311545,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "659152926200918",
        itemID = 153471,
        spellID = 316502,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {26124,26123},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rТорговка праздника Огненного солнцеворота, Поставщица праздника Огненного солнцеворота|n|cFFFFD200Зона: |rДеревня Рут'теран(Тельдрассил),|nЭкзодар,|nСтальгорн,|nШтормград|n|cFFFFD200Цена: |r350 |TInterface\\Icons\\INV_SummerFest_FireFlower.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Огненный солнцеворот",
    },
    {
        hash = "659157221168215",
        itemID = 153472,
        spellID = 316503,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {37674},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rМилая продавщица|n|cFFFFD200Зона: |rОргриммар,|nГромовой Утес,|nПодгород,|nЛуносвет|n|cFFFFD200Цена: |r250 |TInterface\\Icons\\INV_ValentinesCard01.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Любовная лихорадка",
    },
    {
        hash = "663074231341084",
        itemID = 154384,
        spellID = 315420,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {82096,82135,82181},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rБартилий Цум, Аурелий Флос, Иллиан Мраконосец|n|cFFFFD200Зона: |rТол'Гарод|n|cFFFFD200Цена: |r180 |TInterface\\Icons\\achievement_zone_tolbarad.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "663078526308378",
        itemID = 154385,
        spellID = 315418,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {82096,82135,82181},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rБартилий Цум, Аурелий Флос, Иллиан Мраконосец|n|cFFFFD200Зона: |rТол'Гарод|n|cFFFFD200Цена: |r180 |TInterface\\Icons\\achievement_zone_tolbarad.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "663082821275673",
        itemID = 154386,
        spellID = 315417,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {82096,82135,82181},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rБартилий Цум, Аурелий Флос, Иллиан Мраконосец|n|cFFFFD200Зона: |rТол'Гарод|n|cFFFFD200Цена: |r180 |TInterface\\Icons\\achievement_zone_tolbarad.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "663087116242971",
        itemID = 154387,
        spellID = 315419,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {82096,82135,82181},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rБартилий Цум, Аурелий Флос, Иллиан Мраконосец|n|cFFFFD200Зона: |rТол'Гарод|n|cFFFFD200Цена: |r180 |TInterface\\Icons\\achievement_zone_tolbarad.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "663091411208433",
        itemID = 154388,
        spellID = 313585,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {82096,82135,82181},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rБартилий Цум, Аурелий Флос, Иллиан Мраконосец|n|cFFFFD200Зона: |rТол'Гарод|n|cFFFFD200Цена: |r360 |TInterface\\Icons\\achievement_zone_tolbarad.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "663095706175730",
        itemID = 154389,
        spellID = 313586,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {82096,82135,82181},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rБартилий Цум, Аурелий Флос, Иллиан Мраконосец|n|cFFFFD200Зона: |rТол'Гарод|n|cFFFFD200Цена: |r360 |TInterface\\Icons\\achievement_zone_tolbarad.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "675203218988766",
        itemID = 157208,
        spellID = 319198,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 2,
        price = 500,
        shopCategory = 0,
        productID = 24094,
        isActive = 1,
        lootType = 15,
        priceText = "|cFFFFD200Нужно очков голосования: |r500|TInterface\\Store\\mmotop.BLP:16:16|t",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "675207513956103",
        itemID = 157209,
        spellID = 319239,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {33271},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 1,
        priceText = "|cFFFFD200Источник: |rГенерал Везакс|n|cFFFFD200Зона: |rУльдуар|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "1375343017778924",
        itemID = 320222,
        spellID = 319212,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {83500,63319},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rСарри Бил, Сильверин|n|cFFFFD200Зона: |rОргриммар,|nКлоака|n|cFFFFD200Цена: |r31250 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[Можно приобрести у интенданта союзников или у контрабандистов, с меньшими требованиями, но со значительной наценкой.]],
        holidayText = "",
    },
    {
        hash = "1375351607713517",
        itemID = 320224,
        spellID = 319213,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {83500,63320},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rСарри Бил, Антария|n|cFFFFD200Зона: |rПорт Штормграда(Штормград),|nКлоака|n|cFFFFD200Цена: |r31250 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[Можно приобрести у интенданта союзников или у контрабандистов, с меньшими требованиями, но со значительной наценкой.]],
        holidayText = "",
    },
    {
        hash = "1375360197648110",
        itemID = 320226,
        spellID = 319214,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {83500,63321},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rСарри Бил, Тан Тургаден|n|cFFFFD200Зона: |rСтальгорн,|nКлоака|n|cFFFFD200Цена: |r31250 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[Можно приобрести у интенданта союзников или у контрабандистов, с меньшими требованиями, но со значительной наценкой.]],
        holidayText = "",
    },
    {
        hash = "1375368787582703",
        itemID = 320228,
        spellID = 319215,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {83500,63322},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rСарри Бил, Лейалма|n|cFFFFD200Зона: |rПодгород,|nКлоака|n|cFFFFD200Цена: |r31250 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[Можно приобрести у интенданта союзников или у контрабандистов, с меньшими требованиями, но со значительной наценкой.]],
        holidayText = "",
    },
    {
        hash = "1376077457186544",
        itemID = 320393,
        spellID = 319216,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {83500,83361},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rСарри Бил, Отаар|n|cFFFFD200Зона: |rЭкзодар,|nКлоака|n|cFFFFD200Цена: |r31250 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[Можно приобрести у интенданта союзников или у контрабандистов, с меньшими требованиями, но со значительной наценкой.]],
        holidayText = "",
    },
    {
        hash = "1376567083458289",
        itemID = 320507,
        spellID = 319217,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {83500,83404},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rСарри Бил, Си'джи|n|cFFFFD200Зона: |rЛуносвет,|nКлоака|n|cFFFFD200Цена: |r31250 |TINTERFACE\\MONEYFRAME\\UI-GOLDICON.BLP:16:16|t|n",
        descriptionText = [[Можно приобрести у интенданта союзников или у контрабандистов, с меньшими требованиями, но со значительной наценкой.]],
        holidayText = "",
    },
    {
        hash = "162620346778292",
        itemID = 37863,
        spellID = 49844,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {23872},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 1,
        priceText = "|cFFFFD200Источник: |rКорен Худовар|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Хмельной фестиваль",
    },
    {
        hash = "210625196263666",
        itemID = 49040,
        spellID = 67826,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {68067},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 9,
        priceText = "|cFFFFD200Профессия: |rИнженерное дело|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "224416336256620",
        itemID = 52251,
        spellID = 73324,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {24916},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 8,
        priceText = "|cFFFFD200Задание: |rМедальон Джайны|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "675263348532147",
        itemID = 157222,
        spellID = 320435,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "472296079018279",
        itemID = 109965,
        spellID = 313639,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {310589},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 2,
        priceText = "|cFFFFD200Источник: |rЛедяной сундук испытания|n|cFFFFD200Зона: |rЛогово замерзшего снеговика|n|cFFFFD200Цена: |r|n",
        descriptionText = [[Желанный Агрегат По Прямому наКладыванию шАпок. Никогда не пейте с гоблинами в их мастерской. Шанс перепутать пунш с машинной отработкой на Зимний покров равен 97.8%.]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "675254758597553",
        itemID = 157220,
        spellID = 320433,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {310589},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 2,
        priceText = "|cFFFFD200Источник: |rЛедяной сундук испытания|n|cFFFFD200Зона: |rЛогово замерзшего снеговика|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "675259053564850",
        itemID = 157221,
        spellID = 320434,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {310589},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 2,
        priceText = "|cFFFFD200Источник: |rЛедяной сундук испытания|n|cFFFFD200Зона: |rЛогово замерзшего снеговика|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "231606111755206",
        itemID = 53925,
        spellID = 318406,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {81399},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rРабби Снегман|n|cFFFFD200Зона: |rПлощадка Краса(Даларан),|nГлавная дорога(Тол'Гарод),|nОргриммар,|nШтормград|n|cFFFFD200Цена: |r15000 |TInterface\\Icons\\s_marbled_snow.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "231610406722497",
        itemID = 53926,
        spellID = 318401,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {81399},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rРабби Снегман|n|cFFFFD200Зона: |rПлощадка Краса(Даларан),|nГлавная дорога(Тол'Гарод),|nОргриммар,|nШтормград|n|cFFFFD200Цена: |r25000 |TInterface\\Icons\\s_marbled_snow.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "675250463630256",
        itemID = 157219,
        spellID = 320432,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {81399},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rРабби Снегман|n|cFFFFD200Зона: |rПлощадка Краса(Даларан),|nГлавная дорога(Тол'Гарод),|nОргриммар,|nШтормград|n|cFFFFD200Цена: |r25000 |TInterface\\Icons\\s_marbled_snow.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "472291784050984",
        itemID = 109964,
        spellID = 313640,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {81399},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rРабби Снегман|n|cFFFFD200Зона: |rПлощадка Краса(Даларан),|nГлавная дорога(Тол'Гарод),|nОргриммар,|nШтормград|n|cFFFFD200Цена: |r15000 |TInterface\\Icons\\s_marbled_snow.BLP:16:16|t|n",
        descriptionText = [[Желанный Агрегат По Прямому наКладыванию шАпок. Возможно, гномское вдохновение распространяется только на придумывание новых изобретений, и на названия его не хватает.]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "677449486938908",
        itemID = 157731,
        spellID = 373532,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {81399},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 6,
        priceText = "|cFFFFD200Торговец: |rРабби Снегман|n|cFFFFD200Зона: |rПлощадка Краса(Даларан),|nГлавная дорога(Тол'Гарод),|nОргриммар,|nШтормград|n|cFFFFD200Цена: |r25000 |TInterface\\Icons\\s_marbled_snow.BLP:16:16|t|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "265660907500310",
        itemID = 61854,
        spellID = 373526,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {7024},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 7,
        priceText = "|cFFFFD200Достижение: |rВыживание в ледяном разломе VI|n|cFFFFD200Зона: |rЛедяной разлом(Логово замерзшего снеговика)|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "265656612533016",
        itemID = 61853,
        spellID = 373528,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {7025},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 7,
        priceText = "|cFFFFD200Достижение: |rВыживание в ледяном разломе VII|n|cFFFFD200Зона: |rЛедяной разлом(Логово замерзшего снеговика)|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "|cFFFFD200Игровое событие:|r Зимний Покров",
    },
    {
        hash = "677900458503377",
        itemID = 157836,
        spellID = 371921,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {28149},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 1,
        lootType = 8,
        priceText = "|cFFFFD200Задание: |r2000 купонов - Ритуальная книга полной луны|n|n|cFFFFD200Цена: |r|n",
        descriptionText = [[]],
        holidayText = "",
    },
    {
        hash = "170699180583998",
        itemID = 39744,
        spellID = 371774,
        isUsable = true,
        factionSide = 0,
        unique = {},
        colorData = {},
        ownersList = {},
        currency = 0,
        price = 0,
        shopCategory = 0,
        productID = 0,
        isActive = 0,
        lootType = 0,
        priceText = "",
        descriptionText = [[Является одной из наград за прохождение испытания "Один шанс".]],
        holidayText = "",
    },
}

