local SavedValuesPerAccount = {
	"CUSTOM_SESSION_KEYS",
	"SIRUS_LEVEL_UP_SPELLS",
	"SIRUS_SPELLBOOK_SPELL",
	"SIRUS_SPELLBOOK_SKILLLINE",
	"SIRUS_TUTORIAL_KEY",
	"SIRUS_GUILD_RENAME",
	"SIRUS_ARENA_DISTRIBUTION",
	"SIRUS_ARENA_POINTS_PREDICT",
	-- "SIRUS_DEATH_RECAP",
	"SIRUS_MOUNTJOURNAL_FAVORITE_PET",
	"SIRUS_COLLECTION_FAVORITE_PET",
	"SIRUS_RATEDBATTLEGROUND_RANK",
	"SIRUS_RATEDBATTLEGROUND_READY",
	"SIRUS_RATEDBATTLEGROUND_SCORE_DATA",
	"SIRUS_AUCTION_HOUSE_FAVORITE_ITEMS",
	"SIRUS_COLLECTION_COLLECTED_ITEM_APPEARANCES",
	"SIRUS_COLLECTION_FAVORITE_APPEARANCES",
	"SIRUS_COLLECTION_RECEIVED_APPEARANCES",
	"SIRUS_COLLECTION_PLAYER_OUTFITS",
	"SIRUS_COLLECTION_FAVORITE_TOY",
	"SIRUS_KNOWLEDGE_BASE",
	"CUSTOM_SERVER_NEWS",

	"CUSTOM_ROLLED_ITEMS_IN_SHOP",
}

local SavedValuesPerCharacter = {
	"STORE_PRODUCT_CACHE",
	"STORE_DATA_CACHE",
	"CUSTOM_BATTLEPASS_CACHE",

	"TARGET_FRAME_UNLOCKED",
	"PLAYER_FRAME_UNLOCKED",
	"TARGET_FRAME_BUFFS_ON_TOP",
	"FOCUS_FRAME_BUFFS_ON_TOP",
	"PLAYER_FRAME_CASTBARS_SHOWN",
}

function SirusRegisterForSaveFrame_OnLoad(self)
	for _, key in ipairs(SavedValuesPerAccount) do
		RegisterForSave(key)
	end
	for _, key in ipairs(SavedValuesPerCharacter) do
		RegisterForSavePerCharacter(key)
	end
end